CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS notes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE notes DROP CONSTRAINT IF EXISTS notes_user_id_fkey;
ALTER TABLE notes ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE notes ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE notes ALTER COLUMN title SET NOT NULL;
ALTER TABLE notes ALTER COLUMN content SET NOT NULL;
ALTER TABLE notes ALTER COLUMN content SET DEFAULT '';
ALTER TABLE notes ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE notes ALTER COLUMN updated_at SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_notes_user_created ON notes(user_id, created_at DESC);
