FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN apk add --no-cache postgresql-client \
    && npm ci --omit=dev

COPY . .


ENV NODE_ENV=production
EXPOSE 3002

CMD ["npm", "start"]
