FROM node:20-alpine

WORKDIR /app 

COPY package.json ./
COPY package-lock.json ./

RUN apk add --no-cache postgresql-client \
    && npm ci --omit=dev

COPY . .

ENV NODE_ENV=production
EXPOSE 3001

CMD ["npm", "start"]
